const MRWData = [
    "MRW my code doesn't work, then it does, but idk why",
    "MRW I ask someone if they got a haircut and they respond with 'actually I got a lot of them cut'",
    "MRW anybody in the White House says anything",
    "MRW it now gets dark by 5pm thanks to daylight savings time.",
    "MRW my waiter asks me if I want him to refill my Never Ending Pasta Bowl again",
    "MRW the lifeguard says I can't run around the pool.",
    "MRW I've been trying to get off the phone with my dad for 10 minutes",
    "MRW my friend clicks on 5 false 'Download' buttons while torrenting",
    "MRW a website says 'We've noticed you're using an Adblocker'.",
    "MRW an item won't scan in work and the customer says, 'Oh, so I guess it's free then?'",
    "MRW my 13 year old nephew sees my N64 and says '$10 I could kick your ass at smash bros'",
    "MRW I get a $1/hr raise",
    "MRW I eat more than the suggested serving of M&Ms",
    "MRW My calculus professor asks if I'm following along with his lecture",
    "MRW a customer asks to speak to who's in charge, reveal that I'm the manager",
    "MRW it's the first day back from the holidays.",
    "MRW my friend asks how many drinks I had tonight",
    "MRW my aunt gets too drunk at Christmas dinner and falls into the tree, but lands on top of one of my presents",
    "MRW a political shitstorm breaks out in my post, but I'm just basking in my karma",
    "MRW I prepared dinner but my girlfriend 'had a late lunch'",
    "MRW the person sitting next to me at Rogue One asks if any of these characters will be in Guardians of the Galaxy 2",
    "MRW I realize the file I selected was 2.5GB not the 300MB and it just finished downloading to my phone without WiFi",
    "MRW I bought $10 in lottery tickets and won $4 and $7",
    "MRW I meet my GF's parents after she warned me they were crazy",
    "MRW an employee at the grocery store opens an extra checkout lane and waves me over.",
    "MRW my gf says I'm too warm to cuddle with",
    "MRW nobody appreciates my dancing",
    "MRW my friend gets us tickets to a concert for a band I have never heard of",
    "MRW my younger brother beats me at a video game",
    "MRW i browse /r/funny",
    "MRW I'm at work and realise the lady who told her child to 'ask the handsome man for help' was referring to me.",
    "MRW the neighbors have a halloween party and don't invite me",
    "MRW I take away my daughters tablet for 2 days because of misbehavior and she counters by taking daddy kisses away for 2 weeks.",
    "MRW my friend creates a reddit account then asks me how to get a post to the front page",
    "MRW my soon to be ex says 'I didn't get you a Valentine's day card'",
    "MRW I live in the United States and a video says it is not available in my country.",
    "MRW I am watching the Harry Potter movies after I just finished rereading the books",
    "MRW Rick Perry is chosen to replace a nuclear physicist as Secretary of Energy",
    "MRW I have something great to add but the thread is already at 300 comments",
    "MRW my ex sends me a huge long text about how he misses me",
    "MRW my boss wants to promote me to a position without any pay increase",
    "MRW my girlfriend asks what the hell my drunk friend and I are making in the kitchen at 4:30 AM"
  ];

  export { MRWData };
